---
- name: Configure EC2 with Docker and Nginx
  hosts: web
  become: yes
  vars:
    docker_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install prerequisites for adding repos
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - lsb-release
        state: present

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "{{ docker_repo }}"
        state: present

    - name: Update apt cache (again)
      apt:
        update_cache: yes

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: latest

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Stop host Nginx service (if any) to free port 80
      service:
        name: nginx
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Remove existing nginx container if present
      docker_container:
        name: nginx
        state: absent
        force_kill: true

    - name: Pull Nginx image
      docker_image:
        name: nginx
        source: pull

    - name: Run Nginx container
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
